### ISSUE TITLE
Add tool in/with Dcom that makes Level Triggers useable 

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#111]
Level Triggers exist, but they are basically unusable for 2 or more channels, because each channel has a distinct and totally arbitrary DC level. Write a stand-alone python script *or* a component in Dcom that allows us to study the data stream for a brief time, estimate the DC level (e.g. using a median value, so robust against pulses being in the data?), and set each channel's Level Trigger to a specified level *relative to that DC level*. 

Must set up Dastard first in an auto-trigger mode. Then, must listen for triggered records on port BASE+2. Finally, compute DC level and send appropriate trigger config.

**Comment by joefowler** [comment]
Ideally, this runs as a separate Python process, for testing, but can be called by a button from the GUI (say, from the Experts menu?).
```
python examples/set_up_level_triggers.py [--falling] 50
```
This would:
1. Learn from Dastard the relevant info (especially the number of channels). Maybe read the disabled channels list? (Or Dcom passes that in as an optional argument?)
2. Turn all triggers off.
3. Turn on auto trigger at the maximum rate (or maybe 10 ms delay?) Maybe do this for only some max number of channels at a time...16? 64? 256?
4. For the records received from each, compute median, mode, or some other robust estimator of the baseline level.
5. Repeat until we have a value from all N channels.
6. Turn all auto-triggers off. Turn on level triggers, but with each channel having its own distinct level, which is X above the baseline (X=50 in this example; that's the cmd-line argument). Use argument `--falling` to set the sign of the trigger, if given.

Does it make sense to receive the data over port 5502 (or whatever)? Or do we need to store files, etc? I hope files aren't necessary. Ugh.

**Comment by ggggggggg** [comment]
3. we regularly take noise with all channels and 0 ms delay, I just do the simplest easiest thing here until proven not to work (aka do all channels and 0 ms delay)
5. if 3 is simple, 5 doesn't exist
6. just use the sign of the threshold instead of `--falling`

**Comment by joefowler** [comment]
Also still to do:

- [ ] Figure out how to send one command with all levels (might require a dastard change, such as a new RPC call).
- [ ] New default level larger than 50.
