### ISSUE TITLE
Dcom crashes when you disable a channel if number and index are unequal

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#113]
On the Tomcat-1k system, if you click to turn off channel 8287, Dcom crashes saying
```Channel chan8278 triggering is disabled.
Traceback (most recent call last):
    File "/home/pcuser/src/dastardcommander/dastardcommander/trigger_config.py", line 343, in blockTriggering
      self.trigger_state[channelIndex]["ChannelIndices"].remove(channelIndex)
KeyError: 8287
Aborted (core dumped)
```

This clearly has something to do with the difference between channel numbers and indices.

**Comment by ggggggggg** [comment]
Yes, you need to only ever send `ChannelIndex` over the rpc

here is some code that converts from number to index

https://github.com/usnistgov/dastardcommander/blob/7befc011ac5068fe2df89fbacb4971c8b7f894a0/dastardcommander/projectors.py#L89-L102

**Comment by joefowler** [comment]
Thank you. Was just wondering where to find a good example...
