### ISSUE TITLE
Looks like the new disable trigger is not resetting all the EMT-type triggers

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#121]
@ggggggggg and I noticed a non-zero total array-wide trigger rate when some channels were disabled and EMTs were turned on. I though this was fixed but apparently it isn't. Unsure whether this is turning on EMTs that shouldn't be, or failing to turn them off.

**Comment by joefowler** [comment]
Also, we need to stop sending a very large number of messages when Dcom first connects. I believe that each disabled channel is sending a distinct trigger configuration command to the server. It would be better to collect them all and coordinate their configuration with a single command.

**Comment by ggggggggg** [comment]
We shouldn't send anything on dcom startup should we? Dcom can be started as just an observed of state in principle.

**Comment by joefowler** [comment]
I'm glad you made this comment. I was just reaching that exact same conclusion. My only concern is what to do with a channel that Dcom thinks is disabled, but it actually is getting triggers. I think you proposed coloring it, or removing the X, or something.
