### ISSUE TITLE
Don't mark channel grid/map buttons with white X when disabled

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#124]
If the Dcom GUI users clicks channel 63 (say) to disable it, we currently turn that box brown and fill with a white X. But what happens if some other Dcom or other client of Dastard re-enables that channel? In that event, we want it to display its actual rate somehow. Ideas:
* Use a distinct color scale or color. Winter? Maybe the lower half of hot (i.e. black to red).
* Color the rate text white on dark, not dark on light.
* Set rate text to "X" until actual triggers are counted.

**Comment by ggggggggg** [comment]
I don't like option 3 because part of the point is to debug easier, and I won't trust that feature to to work if something is confusing.
