### ISSUE TITLE
Observe Tab grid needs a scroll bar

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#127]
For the 1k TES Tomcat system, we have up to a 32x32 grid of channel numbers in the Observe Tab's Grid Tab. It needs a scroll bar.

**Comment by ggggggggg** [comment]
We could instead have a zoomed out version where we lean more on the color bar and less on the textual count rate? I'm not sure which is likely to be more useful.

**Comment by joefowler** [comment]
Could have, but I finally got this way to work. See next PR....
