### ISSUE TITLE
Need a way to turn off triggering for all misbehaving channels

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#129]
Dcom can turn off misbehaving channels one at a time through GUI clicks, but we need a way to turn off many at once. Proposal:

- [x] Add item in Expert menu labeled "Disable hyperactive channels".
- [x] It starts a dialog:
  - [x] instructing user to ensure there are no active sources of x rays or gamma rays.
  - [x] asking if pulses are rising/falling and how big a reasonable edge trigger should be.
  - [x] with buttons for "Cancel / OK"
- [x] When OK is chosen, it turns off all triggers, turns on the edge triggers as described, and counts for 5-10 seconds.
- [x] Then it turns off all triggers and analyzes the trigger counts.
- [x] Any channels exceeding ~1 trigger per second are added to the disabled list.

**Comment by ggggggggg** [comment]
I think this is too complex. I suggest

1.  Add item in Expert menu labeled "Disable hyperactive channels".
2. It asks if the user has set up the triggering they want, and currently expect a zero trigger rate
3. Any channels exceeding ~1 trigger per second are added to the disabled list.

**Comment by joefowler** [comment]
Understood. But I decided to do it my way, because (starting from the level trigger configuration dialog) your way wasn't actually easier.
