### ISSUE TITLE
JSON requirement in setup.py breaks pip install

### ISSUE THREAD

**Issue by dgmcneel** [usnistgov/dastardcommander#140]
I successfully installed DCOM last week with the same version of python (3.12.2). This week, it will not install. Pip crashes with the error:

ERROR: Could not find a version that satisfies the requirement json (from dastardcommander) (from versions: none)
ERROR: No matching distribution found for json

setup.py was changed last week to include json, yaml, but json is supposed to be a built in module. Not sure about yaml.

**Comment by joefowler** [comment]
Can you try the new branch issue140 to see if that helps?

I did not remember that `json` is a built-in package and must have added it by mistake. (I was in Japan and plead jet lag.) I am also noticing that the package `yaml` should have been listed as `pyyaml`, which is its external name.

**Comment by joefowler** [comment]
@dgmcneel Did you try this proposed fix?

**Comment by dgmcneel** [comment]
Hi Joe,

Yes, that fixes the issue. Thank you!

Daniel

From: Joe Fowler ***@***.***>
Sent: Monday, February 26, 2024 11:17 AM
To: usnistgov/dastardcommander ***@***.***>
Cc: McNeel, Daniel George ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [usnistgov/dastardcommander] JSON requirement in setup.py breaks pip install (Issue #140)


@dgmcneel<https://urldefense.com/v3/__https:/github.com/dgmcneel__;!!Bt8fGhp8LhKGRg!CfBgP-sZqKVidwlbzjyNnECveoLW5wWudxZBJAeTk7v1zyomXRYVf9vJqs3AGOBAJ3oQt1-IzaZBp27CjBumrvXz$> Did you try this proposed fix?
