### ISSUE TITLE
file type info does not update when writing started by other than dcom

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastardcommander#146]
Reproducing steps:

1. Start dcom + dastard
2. start a data source
3. Go to file writing tab
4. Select ljh22 files only
5. send projectors (so off file writing can work)
6. from a different program, send a message to dastard to start file writing with ljh22 and off files
7. Observe file writing tab, it will show that only ljh22 files are being written, but actually both ljh22 and off files are being written

**Comment by joefowler** [comment]
Huh. Interesting fact: DASTARD does _not_ actually send the relevant information to the Dcom instances. Here's the WRITING message contents:
```
{'Active': True, 'Paused': False, 'BasePath': '/tmp/dcom_expt', 
'FilenamePattern': '/tmp/dcom_expt/20240525/0000/20240525_run0000_%s.%s', 
'ExperimentStateFilename': '/tmp/dcom_expt/20240525/0000/20240525_run0000_experiment_state.txt', 'ExperimentStateLabel': 'START', 'ExperimentStateLabelUnixNano': 1716618494458859000, 
'ExternalTriggerFilename': '/tmp/dcom_expt/20240525/0000/20240525_run0000_external_trigger.bin', 
'DataDropFilename': ''}
```

So to solve this observed problem, we'd first need to update DASTARD to include the info in the writing configuration.

**Comment by joefowler** [comment]
Simpler way to reproduce:
1. Start Dastard and _two_ instances of Dcom.
2. Start Data, and put both Dcoms on the Writing tab.
3. Check the LJH22 check box on one Dcom, uncheck it on the other.
4. On the Dcom where the LJH22 is checked, Start writing.
5. You _want_ the other Dcom's LJH22 box to auto-check, but it does not.
