### ISSUE TITLE
ValueError: Precision not allowed in integer format specifier

### ISSUE THREAD

**Issue by DarkTyr** [usnistgov/dastardcommander#153]
Same issue on [v0.2.11](https://github.com/usnistgov/dastardcommander/releases/tag/v0.2.11)  and   [a0de43b](https://github.com/usnistgov/dastardcommander/commit/a0de43b9c3e291fd0f1459bdfbacb3624ee436df)  which is the current head on master
 
This does prevent dastard from being usable on the system. 

dastardcommander has been installed with "pip install -e ." 

Python Version
'''
(cryoQA) pcuser@687Feynman-linux:~/gitrepos/dastardcommander$ python --version
Python 3.10.8
'''

Error
''''
Traceback (most recent call last):
  File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 835, in startStop
    okay = self._start()
  File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 876, in _start
    result = self._startLancero()
  File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 935, in _startLancero
    print(f"Fiber mask: 0x{mask:4.4x}")
ValueError: Precision not allowed in integer format specifier
'''

**Comment by DarkTyr** [comment]
tag v0.2.8 does function, every tag between head and v0.2.8 does not.

**Comment by ggggggggg** [comment]
This is an issue of compatibility between dcom and dastard versions. We keep the masters of both working together, and currently don't have a mechanism to keep track of which older versions work together. So try using the master version of both.

From: Dark Tyr ***@***.***>
Sent: Wednesday, July 31, 2024 10:19 AM
To: usnistgov/dastardcommander ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [usnistgov/dastardcommander] ValueError: Precision not allowed in integer format specifier (Issue #153)


Same issue on v0.2.11<https://github.com/usnistgov/dastardcommander/releases/tag/v0.2.11> and a0de43b<https://github.com/usnistgov/dastardcommander/commit/a0de43b9c3e291fd0f1459bdfbacb3624ee436df> which is the current head on master

This does prevent dastard from being usable on the system.

dastardcommander has been installed with "pip install -e ."

Python Version
'''
(cryoQA) ***@***.***:~/gitrepos/dastardcommander$ python --version
Python 3.10.8
'''

Error
''''
Traceback (most recent call last):
File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 835, in startStop
okay = self._start()
File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 876, in _start
result = self._startLancero()
File "/home/pcuser/gitrepos/dastardcommander/dastardcommander/dc.py", line 935, in _startLancero
print(f"Fiber mask: 0x{mask:4.4x}")
ValueError: Precision not allowed in integer format specifier
'''

-

**Comment by joefowler** [comment]
Yeah, looks like I don't use the correct, modern f-string syntax for zero-padding hex-formatted characters. I think I see what to do, though.

**Comment by joefowler** [comment]
> This is an issue of compatibility between dcom and dastard versions. We keep the masters of both working together, and currently don't have a mechanism to keep track of which older versions work together. So try using the master version of both.

Not correct. This is just a bug. I'm fixing it.
