### ISSUE TITLE
Add option for 0..(N-1) row numbering

### ISSUE THREAD

**Issue by NanoExplorer** [usnistgov/dastardcommander#155]
In the TDM Bolometer systems, row numbering usually starts from 0 (this is how all our wires are labeled and how the system appears in CRINGE). Right now `firstrow = 1` is hard coded, but an additional radio button could be added to allow this to change. https://github.com/usnistgov/dastardcommander/blob/2e3fa5563f41110a60ccebd98b79f14a0ee7ee56/dastardcommander/dc.py#L951 
right now I have hard-coded `firstrow=0` in the Velma system and it isn't causing any other problems.

**Comment by joefowler** [comment]
Fixed by #156
