### ISSUE TITLE
Workflow improvements

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastardcommander#28]
- [x] The workflow items that generate LJH files ought to add a comment (a la the "Comments" button on the writing tab) indicating that these are noise files or pulse files, as needed.
- [x] I crashed DC by asking for a noise analysis without having the right script in place in my ~/.julia/v0.6/..., probably because I haven't updated Pope on my laptop in weeks/months. But this situation should not crash DC. Fixed in 6d0c619.
- [x] It probably ought to search the correct Julia version paths for the scripts. We are calling whatever "julia" lives on the path, so run `julia -v` to learn the major.minor versions. Fixed in f3236ebd58.
- [ ] There should be a way to select number of pulse records and number of noise records (or number of seconds of noise). Maybe that goes in the experts menu. Or we could even think about creating an entire new settings window, if needed.
- [x] I see that the pulse file workflow item lets you stop early (which is great), but I'm not sure it ought to be a modal dialog. Maybe. I see why you'd want that, but you're left unable to do thinks like check the trigger rate tab or the file writing tab, which means you can't see whether some channels are lagging behind. And if somehow data were to stop completely, then what? I guess you stop early and fix the problem. **Make it switch to observe tab during data colleciton?**
- [ ] If restarted, DC needs to remember or figure out that you've already done some of the Workflow items. I have NO IDEA how to handle this; it's something we'll solve later after getting experience using the system, I expect. Simple way: use QSettings within DC. Policy could be, say, that the latest noise and pulse training file is assumed valid, or perhaps only if it's less than 24 or 36 hours old.
- [x] I should note that I wasn't able to test past the noise analysis because of the Julia script problem. I couldn't try the button to pop up the PDFs, say. (Later: tested this on July 12, and it worked.)
- [ ] The noise analysis blocks all other operations of DC. Can that be prevented?

**Comment by joefowler** [comment]
I added the comment text in d2b363c

**Comment by joefowler** [comment]
I'm going to assume this is no longer a real need, as it hasn't been touched in over 4 years!
