### ISSUE TITLE
Need to use new (transposed) definition of projectors

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#73]
`projectors.py` needs to use the new definition of projectors and basis elements in the HDF5 files. The current assumption is the transpose of the new definition.

The new, correct definition is that basis is of size (n_samples, n_basis_elements) and the projectors are the transpose of that.

**Comment by joefowler** [comment]
@ggggggggg: This has been outstanding for a long time. Is it still needed, or did we already fix it somehow?

**Comment by ggggggggg** [comment]
I'm pretty sure it works now, otherwise I probably would have noticed.

**Comment by joefowler** [comment]
Well...I assume this is fixed. If not, we can reopen or start again.
