### ISSUE TITLE
turn this into a pip installable package

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastardcommander#77]
Follow the example of `realtime_gui` to figure out how, basically put all files in a subfolder, use absolute imports for everything, add an entry point to the install so it can be run as a script, eg `dc` from any folder will run. Get the dependencies as close to auto install as easily possible. 

Then for development you would `pip install -e` or run `python setup.py develop`

**Comment by joefowler** [comment]
Fixed by #78.
