### ISSUE TITLE
Record length and pretrigger length needs one widget

### ISSUE THREAD

**Issue by joefowler** [usnistgov/dastardcommander#97]
There are two redundant widgets that let you set record length, pretrigger length, and the pretrigger percentage. This is crazy and impossible to keep updated.

We should create a little widget containing only those 3 spin boxes and their labels, and lay that widget out to be visible in both the Triggering and the Advanced Triggering tabs.

**Comment by ggggggggg** [comment]
No the whole point of the "triggering" one is that it ignores dastard, so its a way of saving what I actually want the triggers to be.

**Comment by joefowler** [comment]
I don't think I follow. Are you saying that the triggering tab contains your plans and intentions, while the advanced triggering tab has the actual values? Do you want to discuss on Slack?

**Comment by joefowler** [comment]
All right. I don't 100% agree with the way this new "simple triggering" tab is done, but I understand what it's all about. A longer-term approach might be to separate this tab out of Dcom to form something like a "Dastard Assistant." 

You collect a small number of commonly-used functions (like reset record length to my fave value, or switch to pulse triggers, or switch back to noise triggers). Nothing in the DA gets any feedback from Dastard. It's a convenience tool that collects your favorite settings and sends them.

But for now, I'll close this issue, as a misunderstanding.
